### ISSUE TITLE
Collapse a node?

### ISSUE THREAD

**Issue by titanix** [mreichhoff/HanziGraph#1]
Hello, this prototype is awesome. One UX issue I had though is that after expending a node that have a lot of edges (不 being the worst offender) the graph becomes hard to read. An way to remove the node from the visualization would be a great addition I think.

Speaking of new features, how about have (an optional) indication, likfe a small number below, of how many neighbors a node have? This would help avoiding the situation I ran with 不 but also help predict the number of new vocabulary.

**Comment by mreichhoff** [comment]
Thanks! I agree those are issues. I’m currently working on a graph with the
top ~50k words based on word frequency that also have entries in CEDICT.
With that one, I’ll limit the edges for each node to 10, but also do
lookups based on the user’s search query, so that valid words that are
searched will still have edges among the hanzi. I think that’ll help limit
the number of nodes quite a bit (and I’d then port that behavior to the
other graphs that are available); just a matter of cleaning up the
definitions file (which would then be used for lookups instead of the set
of words directly in the graph).

I’m also thinking I’ll set it up so that double clicking/tapping a node
that was previously expanded can remove those edges.

The number idea is a good idea too, though I’d like to see how this new
limit looks before I’d set it up.

I’ll keep you posted!

**Comment by mreichhoff** [comment]
alright, I just generated a new graph where the initial load is limited to 10 edges per node. It then creates edges on the fly based on what words it has definitions for. You would need to clear out cache storage, or use [the beta site](https://hanzigraph-prototype.web.app/), then select "Top 50k words" as the character set in the menu in the upper left.

I am going to be working on allowing collapse of a given node next. I'll also be testing out the 10 edge limit (alongside the much larger character set) and will migrate other graphs to that behavior if it looks ok.

**Comment by titanix** [comment]
I tried the new version and yes, thanks, it's more user friendly with a node limit : I tried for instance 子 with would have been a disaster to browse in the old version.

Btw under which license is the code itself? It's not like I'm a proficient JS dev but but it's very connected to some research and ideas I've done in the past so I'm may make so derivate PoC or something one day.

**Comment by mreichhoff** [comment]
I just added the MIT license for the code, though of course the content (in the data folder) remains under the license info in the acknowledgements section of the README. 

I wouldn't call myself a JS dev either, and I haven't made any effort to make the code follow best practices or anything, but definitely feel free to use it or fork it or whatever else!

**Comment by mreichhoff** [comment]
I think this can be closed? I'd be curious to hear if you used it for anything, though.
